baseURL = "http://101.37.161.120/home/"
languageCode = "en-us"
title = "DeFi Journal"
theme = "book"

disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
	BookTheme = 'auto'
	
	BookServiceWorker = true