baseURL = "http://101.37.161.120/home/"
languageCode = "en-us"
title = "DeFi Journal"
theme = "book"

disableKinds = ['taxonomy', 'taxonomyTerm']

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/3-F"
  weight = 10

[params]
	BookTheme = 'auto'
	
	BookServiceWorker = true